### ISSUE TITLE
WordPress system notifications are being captured even though the plugin is configured otherwise

### ISSUE THREAD

**Issue by robert81** [Melapress/admin-notices-manager#91]
Setting in plugin:

![image](https://github.com/wpwhitesecurity/admin-notices-manager/assets/3965050/5c7d460d-af6b-4d9d-b3bd-b4fafe6a8852)

To reproduce:

1) Navigate to a user profile page
2) Delete the nickname:

![image](https://github.com/wpwhitesecurity/admin-notices-manager/assets/3965050/5e366167-5a27-4d2a-86ae-07d99af232a6)

3) Save the user profile

Supposedly you should get a WordPress system message that the nickname is required. Instead the notification shows up for a split second, and then it is captured by the plugin.

![image](https://github.com/wpwhitesecurity/admin-notices-manager/assets/3965050/d3ade9c3-bd07-427f-9b9c-26fed2803da0)

However, the message cannot be read:

![image](https://github.com/wpwhitesecurity/admin-notices-manager/assets/3965050/aee376a6-3799-4467-983b-d26d9532e32c)

**Comment by sdobreff** [comment]
looks like that at some point the stand alone class error has been introduced (which acts the same as notice-error class)
/cib
